Repository patrickjahns/ansible-role-promtail, pull requests merged in 2020-12, with the labels that each got.

#39 Fixes / extends configuration of the positions file
  README.md
  defaults/main.yml
  molecule/default/tests/test_default.py
  molecule/latest/tests/test_latest.py
  tasks/install.yml
Labels: semver:minor

#43 Feature rhel compatability
  .github/workflows/test.yml
  meta/main.yml
  molecule/default/prepare.yml
  molecule/latest/prepare.yml
Labels: enhancement, semver:minor

#45 chore: bump promtail version to 2.1.0
  README.md
  defaults/main.yml
Labels: semver:minor

#48 Remove entry parser setting from example config
  README.md
Labels: documentation

#50 doc: correct links to upstream configuration
  README.md
Labels: documentation
