Repository patrickjahns/ansible-role-promtail, pull requests merged in 2020-05, with the labels that each got.

#12 Feat add file sd config
  README.md
  defaults/main.yml
  molecule/default/tests/test_default.py
  molecule/latest/tests/test_latest.py
  tasks/install.yml
  templates/config.j2
Labels: enhancement, semver:minor

#13 add support for ubuntu disco
  .travis.yml
  meta/main.yml
Labels: enhancement, semver:minor

#15 fix: raise privileges of restart handler
  handlers/main.yml
Labels: bug

#17 Promtail 1.5.0
  README.md
  defaults/main.yml
Labels: enhancement, semver:minor

#19 fix: use sed to correctly extract only the latest changelog entry
  .github/workflows/release.yml
Labels: wontfix

#22 feat: add support for arm architecture
  README.md
  defaults/main.yml
Labels: enhancement, semver:minor
